#!/usr/bin/env python3
"""
Apple App Store review miner using iTunes RSS API.
No authentication required.
"""

import sys
import json
import argparse
import os

sys.path.insert(0, os.path.dirname(__file__))
from utils import (
    match_frustration, dry_run_check, output_result, output_error,
    make_session, safe_get
)

def search_apps(session, keyword, limit=5):
    """Search for apps using iTunes Search API."""
    url = "https://itunes.apple.com/search"
    params = {
        "term": keyword,
        "entity": "software",
        "limit": limit
    }
    resp = safe_get(session, url, params=params)
    if not resp or resp.status_code != 200:
        return []
    
    try:
        data = resp.json()
        return data.get("results", [])
    except json.JSONDecodeError:
        return []

def get_app_reviews(session, app_id, max_reviews=100):
    """Get recent reviews for an app using iTunes RSS API."""
    url = f"https://itunes.apple.com/us/rss/customerreviews/id={app_id}/sortBy=mostRecent/json"
    resp = safe_get(session, url)
    if not resp or resp.status_code != 200:
        return []
        
    try:
        data = resp.json()
        feed = data.get("feed", {})
        entries = feed.get("entry", [])
        
        # entry can be a list, or it might be missing if no reviews
        if not isinstance(entries, list):
            # Sometimes when there's only 1 entry, or no entry, we handle it
            entries = [entries] if entries else []
            
        reviews = []
        for entry in entries:
            # Skip the first entry if it's the app metadata (sometimes happens in older iTunes RSS configs)
            if "im:rating" not in entry:
                continue
                
            try:
                title = entry.get("title", {}).get("label", "")
                content = entry.get("content", {}).get("label", "")
                rating = int(entry.get("im:rating", {}).get("label", "0"))
                author = entry.get("author", {}).get("name", {}).get("label", "Anonymous")
                
                # We want a combined text for frustration matching
                full_text = f"{title}\n{content}"
                
                reviews.append({
                    "review_text": full_text,
                    "title": title,
                    "content": content,
                    "rating": rating,
                    "author": author
                })
                
                if len(reviews) >= max_reviews:
                    break
            except Exception:
                continue
                
        return reviews
    except json.JSONDecodeError:
        return []

def main():
    parser = argparse.ArgumentParser(description="Mine Apple App Store reviews for pain points")
    parser.add_argument("keyword", help="Niche keyword to search in App Store")
    parser.add_argument("--dry-run", action="store_true", help="Show what would be fetched")
    parser.add_argument("--max-apps", type=int, default=5, help="Number of apps to analyze (default: 5)")
    parser.add_argument("--reviews-per-app", type=int, default=100, help="Reviews per app (default: 100)")
    parser.add_argument("--queries", nargs="+", help="Dynamic list of full search queries generated by the agent")
    parser.add_argument("--query-templates", nargs="+", help="Dynamic list of query templates containing {kw}")
    parser.add_argument("--subreddits", nargs="+", help="Subreddits to target for Reddit search (e.g. vegetablegardening gardening)")
    args = parser.parse_args()

    kw = args.keyword
    
    dry_run_check(args, f"Search App Store for '{kw}'", [
        f"iTunes Search API: {kw} (top {args.max_apps} apps)",
        f"iTunes RSS API: recent reviews per app (up to {args.reviews_per_app})",
    ])

    print(f"Searching App Store for: {kw}", file=sys.stderr)
    
    session = make_session()
    
    try:
        apps = search_apps(session, kw, limit=args.max_apps)
        
        all_frustration_reviews = []
        app_details = []
        
        for app in apps:
            app_id = app.get("trackId")
            app_name = app.get("trackName")
            if not app_id:
                continue
                
            app_details.append({
                "app_id": app_id,
                "app_name": app_name,
                "url": app.get("trackViewUrl")
            })
            
            reviews = get_app_reviews(session, app_id, max_reviews=args.reviews_per_app)
            for review in reviews:
                text = review.get("review_text", "")
                
                # Match frustrations
                frustrations = match_frustration(
                    text, 
                    dynamic_filters=getattr(args, "queries", None), 
                    keyword=kw
                )
                
                if frustrations:
                    all_frustration_reviews.append({
                        "app_name": app_name,
                        "app_id": app_id,
                        **review,
                        "frustration_matches": frustrations
                    })
                    
        result_data = {
            "source": "apple_app_store",
            "keyword": kw,
            "apps_analyzed": app_details,
            "total_frustration_reviews_found": len(all_frustration_reviews),
            "frustration_reviews": all_frustration_reviews
        }
        
        output_result(result_data)
        
    except Exception as e:
        output_error("apple_app_store", str(e), keyword=kw)
        sys.exit(1)

if __name__ == "__main__":
    main()
