#!/usr/bin/env python3
"""
Google News miner — finds recent articles and blog posts about a niche.

Uses the Google News RSS feed (free, no auth, no scraping required).
Good for finding industry blog posts, "switched from X" articles, and
complaint-heavy press coverage that doesn't show up in Reddit/SO.

Usage: python scripts/google_news.py <keyword> [options]
"""

import sys
import json
import time
import argparse
import xml.etree.ElementTree as ET
from datetime import datetime

sys.path.insert(0, __file__.rsplit("/", 1)[0])
from utils import (make_session, safe_get, match_frustration,
                   dry_run_check, output_result, output_error)

NEWS_RSS_URL = "https://news.google.com/rss/search"


def fetch_news(session, keyword: str, dynamic_filters: list = None, max_results: int = 30) -> list:
    """Fetch articles from Google News RSS for a keyword."""
    resp = safe_get(session, NEWS_RSS_URL, params={
        "q": keyword,
        "hl": "en-US",
        "gl": "US",
        "ceid": "US:en",
    })
    if resp is None or resp.status_code != 200:
        print(f"Google News RSS failed: {getattr(resp, 'status_code', 'no response')}", file=sys.stderr)
        return []
    try:
        root = ET.fromstring(resp.content)
        items = []
        for item in root.findall(".//item")[:max_results]:
            title = item.findtext("title", "").strip()
            link = item.findtext("link", "").strip()
            description = item.findtext("description", "").strip()
            pub_date = item.findtext("pubDate", "").strip()
            source_el = item.find("source")
            source_name = source_el.text.strip() if source_el is not None else ""

            # Strip HTML from description
            import re
            description_clean = re.sub(r"<[^>]+>", "", description)[:400]

            full_text = title + " " + description_clean
            frustration = match_frustration(full_text, dynamic_filters=dynamic_filters, keyword=keyword)

            items.append({
                "title": title,
                "url": link,
                "snippet": description_clean,
                "published": pub_date,
                "source_name": source_name,
                "frustration_matches": frustration,
            })
        return items
    except ET.ParseError as e:
        print(f"Google News RSS parse error: {e}", file=sys.stderr)
        return []


def main():
    parser = argparse.ArgumentParser(
        description="Mine Google News RSS for recent articles about a niche"
    )
    parser.add_argument("keyword", help="Niche keyword to research")
    parser.add_argument("--dry-run", action="store_true", help="Show what would be fetched")
    parser.add_argument("--max-results", type=int, default=30,
                        help="Max articles to return (default: 30)")
    parser.add_argument("--delay", type=float, default=1.0,
                        help="Seconds between requests (default: 1.0)")
    parser.add_argument("--queries", nargs="+", help="Dynamic list of full search queries generated by the agent")
    parser.add_argument("--query-templates", nargs="+", help="Ignored by this script (for compatibility)")
    parser.add_argument("--subreddits", nargs="+", help="Ignored by this script (for compatibility)")
    args = parser.parse_args()

    kw = args.keyword
    dry_run_check(args, f"Fetch Google News for '{kw}'", [
        f"GET {NEWS_RSS_URL}?q={kw}",
    ])

    session = make_session()
    print(f"Fetching Google News for: {kw}", file=sys.stderr)

    articles = fetch_news(session, kw, dynamic_filters=getattr(args, "queries", None), max_results=args.max_results)

    # Also search with frustration framing to surface complaint articles
    complaint_articles = []
    for suffix in [f"{kw} problems", f"{kw} alternatives", f"why {kw} fails"]:
        time.sleep(args.delay)
        more = fetch_news(session, suffix, dynamic_filters=getattr(args, "queries", None), max_results=10)
        for a in more:
            if not any(x["url"] == a["url"] for x in articles):
                complaint_articles.append(a)

    all_articles = articles + complaint_articles
    frustration_articles = [a for a in all_articles if a["frustration_matches"]]

    # Unique sources
    sources = sorted({a["source_name"] for a in all_articles if a["source_name"]})

    output_result({
        "source": "google_news",
        "keyword": kw,
        "articles_found": len(all_articles),
        "frustration_articles_count": len(frustration_articles),
        "articles": all_articles,
        "frustration_articles": frustration_articles,
        "unique_sources": sources,
    })


if __name__ == "__main__":
    try:
        main()
    except Exception as e:
        output_error("google_news", str(e))
        sys.exit(1)
