#!/usr/bin/env python3
"""
Hacker News miner via Algolia API — finds stories and comments mentioning a niche keyword.

Usage: python scripts/hackernews.py <keyword> [options]
"""

import sys
import json
import time
import argparse

sys.path.insert(0, __file__.rsplit("/", 1)[0])
from utils import make_session, safe_get, match_frustration, dry_run_check, output_result, output_error


HN_SEARCH_URL = "https://hn.algolia.com/api/v1/search"
HN_SEARCH_BY_DATE_URL = "https://hn.algolia.com/api/v1/search_by_date"


def search_hn(session, keyword: str, tags: str, hits_per_page: int = 50, num_pages: int = 2) -> list:
    """Search Hacker News via Algolia."""
    results = []
    for page in range(num_pages):
        resp = safe_get(session, HN_SEARCH_URL, params={
            "query": keyword,
            "tags": tags,
            "hitsPerPage": hits_per_page,
            "page": page,
        })
        if resp is None or resp.status_code != 200:
            break
        try:
            data = resp.json()
            hits = data.get("hits", [])
            results.extend(hits)
            if page >= data.get("nbPages", 1) - 1:
                break
        except Exception as e:
            print(f"HN parse error: {e}", file=sys.stderr)
            break
        time.sleep(0.5)
    return results


def main():
    parser = argparse.ArgumentParser(description="Mine Hacker News stories and comments for pain points")
    parser.add_argument("keyword", help="Niche keyword to research")
    parser.add_argument("--dry-run", action="store_true", help="Show what would be fetched")
    parser.add_argument("--max-stories", type=int, default=50, help="Max stories to retrieve (default: 50)")
    parser.add_argument("--max-comments", type=int, default=150, help="Max comments to retrieve (default: 150)")
    parser.add_argument("--queries", nargs="+", help="Dynamic list of full search queries generated by the agent")
    parser.add_argument("--query-templates", nargs="+", help="Ignored by this script (for compatibility)")
    parser.add_argument("--subreddits", nargs="+", help="Ignored by this script (for compatibility)")
    args = parser.parse_args()

    kw = args.keyword
    
    # We always do a baseline search for the keyword itself
    search_queries = [kw]
    # But if the agent provided specific semantic queries, we search those exactly!
    if getattr(args, "queries", None):
        search_queries.extend(args.queries)
        
    dry_run_check(args, f"Search Hacker News for '{kw}'", [
        f"GET {HN_SEARCH_URL}?query={q}&tags=story" for q in search_queries
    ])

    session = make_session()
    print(f"Searching Hacker News for: {kw}", file=sys.stderr)

    story_hits = []
    ask_hits = []
    show_hits = []
    comment_hits = []

    for query in search_queries:
        print(f"  Searching Algolia for: '{query}'...", file=sys.stderr)
        story_hits.extend(search_hn(session, query, tags="story", hits_per_page=50))
        ask_hits.extend(search_hn(session, query, tags="ask_hn", hits_per_page=50))
        show_hits.extend(search_hn(session, query, tags="show_hn", hits_per_page=50))
        comment_hits.extend(search_hn(session, query, tags="comment", hits_per_page=50, num_pages=3))
        time.sleep(0.5)

    # Format stories
    seen_story_ids = set()
    stories_out = []
    for hit in story_hits + ask_hits + show_hits:
        hn_id = hit.get("objectID", "")
        if hn_id in seen_story_ids:
            continue
        seen_story_ids.add(hn_id)
        tags_list = hit.get("_tags", [])
        story_type = "story"
        if "ask_hn" in tags_list:
            story_type = "ask_hn"
        elif "show_hn" in tags_list:
            story_type = "show_hn"
        stories_out.append({
            "title": hit.get("title", ""),
            "points": hit.get("points", 0),
            "num_comments": hit.get("num_comments", 0),
            "url": hit.get("url", "") or f"https://news.ycombinator.com/item?id={hn_id}",
            "hn_url": f"https://news.ycombinator.com/item?id={hn_id}",
            "created_at": hit.get("created_at", ""),
            "type": story_type,
        })

    stories_out.sort(key=lambda x: x["points"] or 0, reverse=True)

    # Format comments with frustration filter
    frustration_comments = []
    for hit in comment_hits:
        text = hit.get("comment_text", "") or ""
        matches = match_frustration(text, dynamic_filters=getattr(args, "queries", None))
        if matches:
            frustration_comments.append({
                "text": text[:500],
                "points": hit.get("points", 0),
                "story_title": hit.get("story_title", ""),
                "story_url": f"https://news.ycombinator.com/item?id={hit.get('story_id', '')}",
                "created_at": hit.get("created_at", ""),
                "frustration_matches": matches,
            })

    frustration_comments.sort(key=lambda x: x["points"] or 0, reverse=True)

    output_result({
        "source": "hacker_news",
        "keyword": kw,
        "stories_found": len(stories_out),
        "comments_found": len(comment_hits),
        "stories": stories_out[:args.max_stories],
        "frustration_comments": frustration_comments[:args.max_comments],
    })


if __name__ == "__main__":
    try:
        main()
    except Exception as e:
        output_error("hacker_news", str(e))
        sys.exit(1)
