#!/usr/bin/env python3
"""
Reddit complaint miner — searches posts and comments for frustration signals.

Usage: python scripts/reddit.py <keyword> [options]
"""

import sys
import json
import time
import argparse
from datetime import datetime, timezone

sys.path.insert(0, __file__.rsplit("/", 1)[0])
from utils import (make_session, safe_get, load_env_key,
                   match_frustration, dry_run_check, output_result, output_error)


SEARCH_URL = "https://www.reddit.com/search.json"
SUBREDDIT_SEARCH_URL = "https://www.reddit.com/r/{sub}/search.json"
TOKEN_URL = "https://www.reddit.com/api/v1/access_token"




def get_oauth_token(client_id: str, client_secret: str, username: str, password: str, session) -> str:
    """Get OAuth2 access token for Reddit."""
    try:
        resp = session.post(
            TOKEN_URL,
            data={"grant_type": "password", "username": username, "password": password},
            auth=(client_id, client_secret),
            timeout=15,
        )
        if resp.status_code == 200:
            return resp.json().get("access_token")
    except Exception as e:
        print(f"OAuth failed: {e}", file=sys.stderr)
    return None


def search_reddit(session, query: str, subreddit: str = None, after: str = None) -> list:
    """Search Reddit and return list of posts."""
    if subreddit:
        url = SUBREDDIT_SEARCH_URL.format(sub=subreddit)
        params = {"q": query, "restrict_sr": "on", "limit": 100, "sort": "relevance"}
    else:
        url = SEARCH_URL
        params = {"q": query, "limit": 100, "sort": "relevance"}
    if after:
        params["after"] = after

    resp = safe_get(session, url, params=params)
    if resp is None or resp.status_code != 200:
        print(f"Reddit search failed for '{query}': {getattr(resp, 'status_code', 'no response')}", file=sys.stderr)
        return []
    try:
        data = resp.json()
        children = data.get("data", {}).get("children", [])
        return [c["data"] for c in children if c.get("kind") == "t3"]
    except Exception as e:
        print(f"Reddit parse error: {e}", file=sys.stderr)
        return []


def find_relevant_subreddits(session, keyword: str, limit: int = 5) -> list:
    """Search Reddit for subreddits relevant to the keyword."""
    resp = safe_get(session, "https://www.reddit.com/subreddits/search.json",
                    params={"q": keyword, "limit": 10})
    if resp is None or resp.status_code != 200:
        return []
    try:
        children = resp.json().get("data", {}).get("children", [])
        subs = []
        for child in children:
            data = child.get("data", {})
            name = data.get("display_name", "")
            subscribers = data.get("subscribers", 0)
            if name and subscribers > 5000:
                subs.append(name)
        return subs[:limit]
    except Exception:
        return []


def format_post(post: dict, dynamic_filters: list = None, keyword: str = "") -> dict:
    """Extract relevant fields from a raw Reddit post."""
    selftext = post.get("selftext", "") or ""
    text_preview = selftext[:500]
    full_text = post.get("title", "") + " " + selftext
    matches = match_frustration(full_text, dynamic_filters=dynamic_filters, keyword=keyword)
    created = post.get("created_utc", 0)
    try:
        date_str = datetime.fromtimestamp(created, tz=timezone.utc).strftime("%Y-%m-%d")
    except Exception:
        date_str = str(created)
    return {
        "title": post.get("title", ""),
        "selftext_preview": text_preview,
        "score": post.get("score", 0),
        "num_comments": post.get("num_comments", 0),
        "subreddit": post.get("subreddit", ""),
        "url": "https://reddit.com" + post.get("permalink", ""),
        "created_utc": date_str,
        "frustration_matches": matches,
    }


def main():
    parser = argparse.ArgumentParser(description="Mine Reddit for pain points and frustration signals")
    parser.add_argument("keyword", help="Niche keyword to research")
    parser.add_argument("--dry-run", action="store_true", help="Show what would be fetched")
    parser.add_argument("--subreddits", nargs="+", help="Limit search to specific subreddits")
    parser.add_argument("--limit", type=int, default=50, help="Max posts to return (default: 50)")
    parser.add_argument("--delay", type=float, default=1.0, help="Seconds between requests (default: 1.0)")
    parser.add_argument("--queries", nargs="+", help="Dynamic list of full search queries generated by the agent")
    args = parser.parse_args()

    kw = args.keyword
    queries = [kw]
    
    # Actually SEARCH the API for the semantic queries the agent generated!
    if getattr(args, "queries", None):
        queries.extend(args.queries)

    dry_run_check(args, f"Search Reddit for '{kw}' frustration signals", [
        f"GET {SEARCH_URL}?q={q}" for q in queries
    ])

    # Auth setup
    client_id = load_env_key("REDDIT_CLIENT_ID")
    client_secret = load_env_key("REDDIT_CLIENT_SECRET")
    username = load_env_key("REDDIT_USERNAME")
    password = load_env_key("REDDIT_PASSWORD")

    user_agent = f"niche-discovery/1.0 (by /u/{username or 'anonymous'})"
    session = make_session(user_agent)

    auth_method = "anonymous"
    if all([client_id, client_secret, username, password]):
        print("Attempting Reddit OAuth...", file=sys.stderr)
        token = get_oauth_token(client_id, client_secret, username, password, session)
        if token:
            session.headers.update({"Authorization": f"Bearer {token}"})
            session.headers.update({"User-Agent": user_agent})
            # Switch to OAuth base URL
            auth_method = "oauth"
            print("OAuth authenticated (60 req/min)", file=sys.stderr)
        else:
            print("OAuth failed, falling back to anonymous (10 req/min)", file=sys.stderr)
    else:
        print("No Reddit credentials found, using anonymous access (10 req/min)", file=sys.stderr)

    # Collect posts
    all_posts = {}

    # Auto-detect relevant subreddits if none specified
    if args.subreddits:
        subreddits_to_search = args.subreddits
    else:
        print(f"Auto-detecting relevant subreddits for '{kw}'...", file=sys.stderr)
        detected = find_relevant_subreddits(session, kw)
        if detected:
            print(f"Found subreddits: {detected}", file=sys.stderr)
            subreddits_to_search = [None] + detected  # global search + subreddit-specific
        else:
            subreddits_to_search = [None]

    for query in queries:
        for sub in subreddits_to_search:
            print(f"Searching: '{query}'" + (f" in r/{sub}" if sub else ""), file=sys.stderr)
            posts = search_reddit(session, query, subreddit=sub)
            for post in posts:
                post_id = post.get("id", "")
                if post_id and post_id not in all_posts:
                    all_posts[post_id] = format_post(post, dynamic_filters=getattr(args, "queries", None), keyword=kw)
            time.sleep(args.delay)

    # Sort: frustration matches first, then by score — keeps relevant pain points above viral off-topic posts
    sorted_posts = sorted(
        all_posts.values(),
        key=lambda p: (len(p["frustration_matches"]) > 0, p["score"]),
        reverse=True,
    )[:args.limit]
    frustration_posts = [p for p in sorted_posts if p["frustration_matches"]]

    # Top subreddits
    sub_counts = {}
    for p in sorted_posts:
        sub = p["subreddit"]
        sub_counts[sub] = sub_counts.get(sub, 0) + 1
    top_subreddits = sorted([{"name": k, "count": v} for k, v in sub_counts.items()],
                            key=lambda x: x["count"], reverse=True)[:10]

    output_result({
        "source": "reddit",
        "keyword": kw,
        "auth_method": auth_method,
        "posts": sorted_posts,
        "total_found": len(all_posts),
        "frustration_posts_count": len(frustration_posts),
        "top_subreddits": top_subreddits,
    })


if __name__ == "__main__":
    try:
        main()
    except Exception as e:
        output_error("reddit", str(e))
        sys.exit(1)
