#!/usr/bin/env python3
"""
Full niche-discovery session runner.

Runs all scripts in order, saves results to ./results/, then synthesizes
with analyze.py. Replaces the manual step-by-step workflow.

Usage:
  python scripts/run_all.py "keyword"           # full run
  python scripts/run_all.py "keyword" --quick   # Step 1 only (quick check)
  python scripts/run_all.py "keyword" --no-apify  # skip Apify (saves credit)
"""

import sys
import os
import subprocess
import json
import time
import shutil
import argparse
import concurrent.futures

SKILL_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
SCRIPTS_DIR = os.path.join(SKILL_ROOT, "scripts")
RESULTS_DIR = os.path.join(SKILL_ROOT, "results")
PYTHON = os.path.join(SKILL_ROOT, ".venv", "bin", "python")
if not os.path.exists(PYTHON):
    PYTHON = sys.executable

QUICK_SCRIPTS = ["autocomplete", "trends", "serp", "cpc"]

FULL_SCRIPTS = [
    "reddit",
    "stackoverflow",
    "github_issues",
    "hackernews",
    "google_news",
    "playstore",
    "appstore",
    "youtube_comments",
    "youtube_transcripts",
    "wordpress",
]



def run_script(script: str, keyword: str, extra_args: list = None) -> tuple:
    """Run a script, return (success: bool, summary: str)."""
    cmd = [PYTHON, os.path.join(SCRIPTS_DIR, f"{script}.py"), keyword]
    if extra_args:
        cmd.extend(extra_args)

    result = subprocess.run(cmd, capture_output=True, text=True)
    stdout = result.stdout.strip()
    success = result.returncode == 0

    # Check if the output JSON contains an error
    if stdout:
        try:
            data = json.loads(stdout)
            if "error" in data:
                return False, data["error"]
        except (json.JSONDecodeError, TypeError):
            pass

    if not success:
        err_snippet = result.stderr.strip().splitlines()[-1] if result.stderr.strip() else "unknown error"
        return False, err_snippet

    return True, "ok"


def check_early_exit(keyword: str) -> bool:
    """Return True if signal is too weak to continue."""
    for fname in os.listdir(RESULTS_DIR):
        if not fname.startswith("google_autocomplete"):
            continue
        try:
            with open(os.path.join(RESULTS_DIR, fname)) as f:
                data = json.load(f)
            count = data.get("count", 0)
            reframes = data.get("low_signal_reframes", [])
            if count < 3:
                print(f"\n⚠  Low autocomplete signal: only {count} suggestion(s) found.", file=sys.stderr)
                if reframes:
                    print("   Suggested reframes to try instead:", file=sys.stderr)
                    for r in reframes:
                        print(f"     • '{r['keyword']}' ({r['suggestion_count']} suggestions)", file=sys.stderr)
                return True
        except Exception:
            pass
    return False


def print_separator(label: str):
    print(f"\n{'─' * 50}", file=sys.stderr)
    print(f"  {label}", file=sys.stderr)
    print(f"{'─' * 50}", file=sys.stderr)


def main():
    parser = argparse.ArgumentParser(
        description="Run all niche-discovery scripts and synthesize results"
    )
    parser.add_argument("keyword", help="Niche keyword to research")
    parser.add_argument("--quick", action="store_true",
                        help="Step 1 only — quick demand check")
    parser.add_argument("--no-apify", action="store_true",
                        help="Skip Apify scrapers (saves free credit)")
    parser.add_argument("--queries", nargs="+", help="Dynamic list of full search queries generated by the agent")
    parser.add_argument("--query-templates", nargs="+", help="Dynamic list of query templates containing {kw}")
    parser.add_argument("--subreddits", nargs="+", help="Subreddits to target for Reddit search (e.g. vegetablegardening gardening)")
    args = parser.parse_args()

    kw = args.keyword

    # Always clear previous results to avoid mixing data from different searches
    if os.path.isdir(RESULTS_DIR):
        shutil.rmtree(RESULTS_DIR)
        print("Cleared previous results.", file=sys.stderr)
    os.makedirs(RESULTS_DIR, exist_ok=True)

    report = {"keyword": kw, "ok": [], "failed": [], "skipped": []}
    start_time = time.time()

    # ── Step 1: Quick Check ───────────────────────────────────────────────────
    print_separator(f"Step 1 — Quick Check  |  '{kw}'")
    
    quick_extra_args = []
    if getattr(args, "query_templates", None):
        quick_extra_args.extend(["--query-templates"] + args.query_templates)

    for script in QUICK_SCRIPTS:
        if script == "autocomplete":
            ok, msg = run_script(script, kw, extra_args=quick_extra_args)
        else:
            ok, msg = run_script(script, kw)
            
        status = "✓" if ok else "✗"
        print(f"  [{status}] {script:<20} {'' if ok else msg}", file=sys.stderr)
        (report["ok"] if ok else report["failed"]).append(script)

    # Early exit if signal is too weak
    if check_early_exit(kw):
        print("\n  Consider changing the keyword before continuing.", file=sys.stderr)
        if args.quick:
            _print_summary(report, start_time)
            return
        print("  Continuing anyway (use --quick to stop here).", file=sys.stderr)

    if args.quick:
        _print_summary(report, start_time)
        return

    # ── Step 2: Full Mine ─────────────────────────────────────────────────────
    print_separator("Step 2 — Full Mine")
    fetcher_extra_args = []
    if getattr(args, "queries", None):
        fetcher_extra_args.extend(["--queries"] + args.queries)
    if getattr(args, "subreddits", None):
        fetcher_extra_args.extend(["--subreddits"] + args.subreddits)

    # Run fetchers concurrently
    with concurrent.futures.ThreadPoolExecutor(max_workers=len(FULL_SCRIPTS)) as executor:
        future_to_script = {
            executor.submit(run_script, script, kw, fetcher_extra_args): script 
            for script in FULL_SCRIPTS
        }
        
        for future in concurrent.futures.as_completed(future_to_script):
            script = future_to_script[future]
            try:
                ok, msg = future.result()
                status = "✓" if ok else "✗"
                print(f"  [{status}] {script:<20} {'' if ok else msg}", file=sys.stderr)
                (report["ok"] if ok else report["failed"]).append(script)
            except Exception as exc:
                print(f"  [✗] {script:<20} generated an exception: {exc}", file=sys.stderr)
                report["failed"].append(script)

    if not args.no_apify:
        print(f"\n  Apify scrapers:", file=sys.stderr)
        ok, msg = run_script("apify_scrape", kw, extra_args=fetcher_extra_args)
        status = "✓" if ok else "✗"
        print(f"  [{status}] apify_google_search  {'' if ok else msg}", file=sys.stderr)
        (report["ok"] if ok else report["failed"]).append("apify_google_search")
    else:
        report["skipped"].append("apify (--no-apify)")

    _print_summary(report, start_time)


def _print_summary(report: dict, start_time: float):
    elapsed = int(time.time() - start_time)
    ok = len(report["ok"])
    failed = len(report["failed"])
    skipped = len(report["skipped"])
    print(f"\n{'═' * 50}", file=sys.stderr)
    print(f"  Session complete in {elapsed}s  —  "
          f"{ok} ok / {failed} failed / {skipped} skipped", file=sys.stderr)
    if report["failed"]:
        print(f"  Failed: {', '.join(report['failed'])}", file=sys.stderr)
    if report["skipped"]:
        print(f"  Skipped: {', '.join(report['skipped'])}", file=sys.stderr)
    print(f"  Results saved to: results/", file=sys.stderr)
    print(f"{'═' * 50}", file=sys.stderr)


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\nInterrupted.", file=sys.stderr)
        sys.exit(1)
