#!/usr/bin/env python3
"""
WordPress.org Plugin miner — finds plugins and scrapes low-star support/reviews.

Usage: python scripts/wordpress.py <keyword> [options]
"""

import sys
import json
import time
import argparse

sys.path.insert(0, __file__.rsplit("/", 1)[0])
from utils import make_session, safe_get, match_frustration, dry_run_check, output_result, output_error

try:
    from bs4 import BeautifulSoup
    BS4_AVAILABLE = True
except ImportError:
    BS4_AVAILABLE = False

PLUGIN_SEARCH_URL = "https://api.wordpress.org/plugins/info/1.2/"
REVIEWS_URL = "https://wordpress.org/support/plugin/{slug}/reviews/"


def search_plugins(session, keyword: str, per_page: int = 10) -> list:
    """Search WordPress.org Plugin directory."""
    resp = safe_get(session, PLUGIN_SEARCH_URL, params={
        "action": "query_plugins",
        "search": keyword,
        "per_page": per_page,
        "fields[active_installs]": 1,
        "fields[rating]": 1,
        "fields[num_ratings]": 1,
    })
    if resp is None or resp.status_code != 200:
        return []
    try:
        data = resp.json()
        return data.get("plugins", [])
    except Exception as e:
        print(f"WP plugin search parse error: {e}", file=sys.stderr)
        return []


def scrape_reviews(session, slug: str, plugin_name: str, dynamic_filters: list = None, max_pages: int = 3) -> list:
    """Scrape 1-3 star reviews from WordPress.org plugin support page."""
    if not BS4_AVAILABLE:
        print("Warning: beautifulsoup4 not installed, skipping review scraping", file=sys.stderr)
        return []

    reviews = []
    for rating in [1, 2, 3]:
        url = REVIEWS_URL.format(slug=slug)
        resp = safe_get(session, url, params={"filter": rating})
        if resp is None or resp.status_code != 200:
            continue
        soup = BeautifulSoup(resp.text, "html.parser")
        review_divs = soup.select(".review")
        for div in review_divs:
            text_el = div.select_one(".review-body")
            if not text_el:
                continue
            text = text_el.get_text(separator=" ", strip=True)
            matches = match_frustration(text, dynamic_filters=dynamic_filters)
            reviews.append({
                "plugin_name": plugin_name,
                "review_text": text[:500],
                "rating": rating,
                "frustration_matches": matches,
            })
        time.sleep(1.0)

    return reviews


def main():
    parser = argparse.ArgumentParser(description="Mine WordPress.org plugins for complaints and pain points")
    parser.add_argument("keyword", help="Niche keyword to search in WordPress plugins")
    parser.add_argument("--dry-run", action="store_true", help="Show what would be fetched")
    parser.add_argument("--max-plugins", type=int, default=5, help="Number of plugins to analyze (default: 5)")
    parser.add_argument("--queries", nargs="+", help="Dynamic list of full search queries generated by the agent")
    parser.add_argument("--query-templates", nargs="+", help="Dynamic list of query templates containing {kw}")
    parser.add_argument("--subreddits", nargs="+", help="Ignored by this script (for compatibility)")
    args = parser.parse_args()

    kw = args.keyword
    dry_run_check(args, f"Search WordPress.org plugins for '{kw}'", [
        f"GET {PLUGIN_SEARCH_URL}?action=query_plugins&search={kw}",
        f"Scrape {REVIEWS_URL.format(slug='<slug>')} for ratings 1, 2, 3 (top {args.max_plugins} plugins)",
    ])

    session = make_session()
    print(f"Searching WordPress.org plugins for: {kw}", file=sys.stderr)
    plugins = search_plugins(session, kw, per_page=args.max_plugins * 2)

    if not plugins:
        output_result({
            "source": "wordpress_plugins",
            "keyword": kw,
            "plugins_found": 0,
            "plugins": [],
            "frustration_reviews": [],
        })
        return

    plugins = plugins[:args.max_plugins]
    plugins_meta = []
    all_reviews = []

    for p in plugins:
        slug = p.get("slug", "")
        name = p.get("name", "")
        plugins_meta.append({
            "name": name,
            "slug": slug,
            "active_installs": p.get("active_installs", 0),
            "rating": p.get("rating", 0) / 20,  # WP stores rating as 0-100
            "num_ratings": p.get("num_ratings", 0),
        })
        print(f"Scraping reviews for: {name}", file=sys.stderr)
        reviews = scrape_reviews(session, slug, name, dynamic_filters=getattr(args, "queries", None))
        all_reviews.extend(reviews)

    output_result({
        "source": "wordpress_plugins",
        "keyword": kw,
        "plugins_found": len(plugins_meta),
        "plugins": plugins_meta,
        "frustration_reviews": all_reviews,
    })


if __name__ == "__main__":
    try:
        main()
    except Exception as e:
        output_error("wordpress_plugins", str(e))
        sys.exit(1)
