#!/usr/bin/env python3
"""
YouTube comments miner — finds frustration signals in video comments.

Usage: python scripts/youtube_comments.py <keyword> [options]
"""

import sys
import json
import time
import argparse

sys.path.insert(0, __file__.rsplit("/", 1)[0])
from utils import (make_session, safe_get, load_env_key,
                   match_frustration, dry_run_check, output_result, output_error)


SEARCH_URL = "https://www.googleapis.com/youtube/v3/search"
COMMENTS_URL = "https://www.googleapis.com/youtube/v3/commentThreads"
VIDEO_URL = "https://www.googleapis.com/youtube/v3/videos"


def search_videos(session, keyword: str, api_key: str, max_results: int = 10) -> list:
    """Search YouTube for videos matching keyword."""
    resp = safe_get(session, SEARCH_URL, params={
        "part": "snippet",
        "q": keyword,
        "type": "video",
        "key": api_key,
        "maxResults": max_results,
        "order": "relevance",
    })
    if resp is None or resp.status_code != 200:
        print(f"YouTube search error: {getattr(resp, 'status_code', 'no response')}", file=sys.stderr)
        return []
    data = resp.json()
    videos = []
    for item in data.get("items", []):
        snippet = item.get("snippet", {})
        videos.append({
            "video_id": item["id"]["videoId"],
            "title": snippet.get("title", ""),
            "channel": snippet.get("channelTitle", ""),
            "published_at": snippet.get("publishedAt", ""),
            "url": f"https://www.youtube.com/watch?v={item['id']['videoId']}",
        })
    return videos


def get_video_stats(session, video_ids: list, api_key: str) -> dict:
    """Get view counts and like counts for videos."""
    if not video_ids:
        return {}
    resp = safe_get(session, VIDEO_URL, params={
        "part": "statistics",
        "id": ",".join(video_ids),
        "key": api_key,
    })
    if resp is None or resp.status_code != 200:
        return {}
    stats = {}
    for item in resp.json().get("items", []):
        vid = item["id"]
        s = item.get("statistics", {})
        stats[vid] = {
            "view_count": int(s.get("viewCount", 0)),
            "like_count": int(s.get("likeCount", 0)),
        }
    return stats


def fetch_comments(session, video_id: str, api_key: str, max_results: int = 100) -> list:
    """Fetch top-level comments for a video."""
    resp = safe_get(session, COMMENTS_URL, params={
        "part": "snippet",
        "videoId": video_id,
        "key": api_key,
        "maxResults": max_results,
        "order": "relevance",
    })
    if resp is None:
        return []
    if resp.status_code == 403:
        print(f"Comments disabled for video {video_id}", file=sys.stderr)
        return []
    if resp.status_code != 200:
        print(f"Comments error {resp.status_code} for {video_id}", file=sys.stderr)
        return []
    comments = []
    for item in resp.json().get("items", []):
        top = item.get("snippet", {}).get("topLevelComment", {}).get("snippet", {})
        comments.append({
            "text": top.get("textDisplay", ""),
            "like_count": top.get("likeCount", 0),
            "published_at": top.get("publishedAt", ""),
        })
    return comments


def main():
    parser = argparse.ArgumentParser(description="Mine YouTube comments for pain points")
    parser.add_argument("keyword", help="Niche keyword to research")
    parser.add_argument("--dry-run", action="store_true", help="Show what would be fetched")
    parser.add_argument("--max-videos", type=int, default=10, help="Number of videos to search (default: 10)")
    parser.add_argument("--max-comments", type=int, default=100, help="Comments per video (default: 100)")
    parser.add_argument("--queries", nargs="+", help="Dynamic list of full search queries generated by the agent")
    parser.add_argument("--query-templates", nargs="+", help="Ignored by this script (for compatibility)")
    parser.add_argument("--subreddits", nargs="+", help="Ignored by this script (for compatibility)")
    args = parser.parse_args()

    kw = args.keyword
    search_queries = [kw]
    if getattr(args, "queries", None):
        search_queries.extend(args.queries)

    dry_run_check(args, f"Fetch YouTube comments for '{kw}'", [
        f"YouTube Search API: {SEARCH_URL}?q={q}&maxResults={args.max_videos}" for q in search_queries
    ] + [f"YouTube CommentThreads API: {COMMENTS_URL}?videoId=<id>&maxResults={args.max_comments}"])

    api_key = load_env_key("YOUTUBE_API_KEY")
    if not api_key:
        output_error("youtube_comments", "YOUTUBE_API_KEY not set", keyword=kw)
        sys.exit(1)

    session = make_session()
    quota_used = 0

    print(f"Searching YouTube for: {kw}", file=sys.stderr)
    
    videos = []
    seen_video_ids = set()
    
    # Divide max videos evenly among queries so we don't blow the quota
    per_query_limit = max(1, args.max_videos // len(search_queries))

    for query in search_queries:
        print(f"  Searching YouTube for: '{query}'...", file=sys.stderr)
        query_videos = search_videos(session, query, api_key, max_results=per_query_limit)
        quota_used += 100  # search costs 100 units
        
        for v in query_videos:
            if v["video_id"] not in seen_video_ids:
                seen_video_ids.add(v["video_id"])
                videos.append(v)
                
        time.sleep(0.5)

    if not videos:
        output_error("youtube_comments", "No videos found", keyword=kw)
        sys.exit(1)

    # Get stats
    video_ids = [v["video_id"] for v in videos]
    stats = get_video_stats(session, video_ids, api_key)
    quota_used += 1
    for v in videos:
        v.update(stats.get(v["video_id"], {}))

    # Fetch comments and scan for frustration
    all_frustration_comments = []
    total_comments = 0

    for video in videos:
        vid_id = video["video_id"]
        print(f"Fetching comments for: {video['title'][:60]}", file=sys.stderr)
        comments = fetch_comments(session, vid_id, api_key, max_results=args.max_comments)
        quota_used += 1
        total_comments += len(comments)
        time.sleep(0.5)

        for c in comments:
            matches = match_frustration(c["text"], dynamic_filters=getattr(args, "queries", None))
            if matches:
                all_frustration_comments.append({
                    "video_title": video["title"],
                    "video_url": video["url"],
                    "comment_text": c["text"][:500],
                    "like_count": c["like_count"],
                    "frustration_matches": matches,
                })

    # Sort frustration comments by like count
    all_frustration_comments.sort(key=lambda x: x["like_count"], reverse=True)

    output_result({
        "source": "youtube_comments",
        "keyword": kw,
        "videos_searched": len(videos),
        "total_comments_scanned": total_comments,
        "frustration_comments": all_frustration_comments[:100],
        "quota_used": quota_used,
        "videos": [
            {
                "title": v["title"],
                "url": v["url"],
                "view_count": v.get("view_count", 0),
                "like_count": v.get("like_count", 0),
                "published_at": v.get("published_at", ""),
            }
            for v in videos
        ],
    })


if __name__ == "__main__":
    try:
        main()
    except Exception as e:
        output_error("youtube_comments", str(e))
        sys.exit(1)
